### PR TITLE
package: add babel-register

### PR DESCRIPTION
**Pull request by AliMD**
About #137

### CODE REVIEW

**Comment by AliMD** [comment]
The is no need to install babel separate for gulp!
https://babeljs.io/docs/setup

Should i remove it ?

**Comment by ericmdantas** [comment]
What do you mean by "there is no need"? Babel still has to be a dependency so you can use `gulpfile.babel.js` without explicitly compiling your code to `es5`, no?

**Comment by AliMD** [comment]
I think you just need gulp-babel and babel-register in babel v6 and don`t need babel module.

**Comment by AliMD** [comment]
> but the problem seems to be different.

I know that i find the problem and its about clients tasks but my first issue is about babel-register

**Comment by AliMD** [comment]
> What do you mean by "there is no need"

Please check [this article](http://jamesknelson.com/teaching-gulp-es6-with-babel-6/), all of nececory modules are `babel-preset-es2015` and `babel-core` or `babel-register`  not `babel` anymore

**Comment by ericmdantas** [comment]
I see. Feel free to change that too, but can you target it to `1.8`, please? It'll be out this week.

**Comment by AliMD** [comment]
> can you target it to 1.8, please?
sure

**Pull request closed without merging**
