### PR TITLE
Added required dev dependencies to package.json

### PR DESCRIPTION
**Pull request by Kablex**

### CODE REVIEW

**Comment by ericmdantas** [comment]
Hello!

Why would `reflect-metadata` be a dependency?

**Comment by Kablex** [comment]
Hello!

When I do NPM Install after the generate with MEANT (ng2) and no https I must install it cause ng2 required. Check it out, maybe is just my problem. ;)

Thanks for your work, the generator is awesome.

**Comment by Kablex** [comment]
Thanks to you!

You are right, closing the conversation. Have a nice day and congratulations for the generator.

**Comment by ericmdantas** [comment]
You're welcome!

And thanks for the contribution once again :smile:

**Pull request closed without merging**
