### PR TITLE
Found a temporary at least fix for typescript errors on compilation

### PR DESCRIPTION
**Pull request by Dev-Force**

### CODE REVIEW

**Comment by ericmdantas** [comment]
Well, that's interesting.

So, we're only left with the content-length one or there's no one left?

Also, could you please target it to `1.7.15` in `package.json`, so I can get it and release it right away.

**Comment by Dev-Force** [comment]
sure gimme a sec
but isnt it 1.7.14??
ur last version is 13

**Comment by ericmdantas** [comment]
Not anymore, I was fixing a bug with `aliv` in OSX and had to release `1.7.14` 😄

**Comment by ericmdantas** [comment]
But you can leave the version as it is, I can fix it on my end - since I'll have to publish a new one.

**Comment by Dev-Force** [comment]
done

**Comment by ericmdantas** [comment]
Thanks!

**Comment by Dev-Force** [comment]
no problem :)

**Pull request merged**
