### PR TITLE
Made node ts and ng2 work together. fixed several bugs

### PR DESCRIPTION
**Pull request by Dev-Force**

### CODE REVIEW

**Comment by ericmdantas** [comment]
That's awesome, @Dev-Force! Thanks!

Just a question, does that fix https://github.com/ericmdantas/generator-ng-fullstack/issues/79?

**Comment by Dev-Force** [comment]
well i didnt understand what exactly was wrong with #79 , i just did a 'typings install' and all were fine.
could u explain me a bit?

**Comment by ericmdantas** [comment]
It led to errors when compiling, such as: https://github.com/ericmdantas/generator-ng-fullstack/issues/109

**Comment by Dev-Force** [comment]
i just see what u meant. for the #79 it doesnt fix all the errors. I fixed them all except 5.

server\api\todo\controller\todo-controller.ts(7,10): 
error TS2339: Property 'getAll' does not exist on type 'Model<Document>'.

server\api\todo\controller\todo-controller.ts(16,10): 
error TS2339: Property 'createTodo' does not exist on type 'Model<Document>'.

server\api\todo\controller\todo-controller.ts(25,8): 
error TS2339: Property 'deleteTodo' does not exist on type 'Model<Document>'.

server\config\routes.conf.ts(6,32): 
error TS2307: Cannot find module 'express-content-length-validator'.

server\server.ts(17,24):
error TS2345: Argument of type 'typeof e' is not assignable to parameter of type 'Express'.

But the application is working fine.
I think that the first 3, are not actual errors. I think they are caused by DefinitelyTyped type definition.
They possibly havent written something about model methods and statics.
I ve searched everywere but i didnt find a solution yet.
The last one is because RoutesConfig init function doesnt even need the second argument.

**Comment by ericmdantas** [comment]
Cool, cool. We'll tackle that little by little. 

Thanks for the PR once again.

**Comment by Dev-Force** [comment]
thats right, your welcome. You ve started a nice project that could help a lot of people that are trying to kickstart a MEAN stack with angular 2 and ts. I didnt find something more useful or popular and said "why not helping" :)

**Comment by ericmdantas** [comment]
Thanks! 

That was the main idea, we all start somewhere and it's always good to have help around. Feel free to join in discussions and proprose changes anytime.

**Comment by Dev-Force** [comment]
Sure! gonna sleep cu around

**Comment by ericmdantas** [comment]
See ya.

**Comment by Dev-Force** [comment]
hey @ericmdantas, as far as the first 3 errors are concerned, i found this, but i didnt successfully make it work. can u check it out? 
http://stackoverflow.com/questions/28379788/classes-and-interfaces-to-write-typed-models-and-schemas-of-mongoose-in-typescri

**Comment by ericmdantas** [comment]
Interesting, I haven't tried that.

I guess I won't be able to try it out today, but tomorrow I'll give it a go. 

Thanks for the link!

**Comment by ericmdantas** [comment]
Maybe we could also cast the call in the controller and see what happens. Something like: 

```ts
(<mongoose.Document>TodoDao).createTodo...
```

**Comment by Dev-Force** [comment]
nice idea. if u try it out let me know

**Comment by Dev-Force** [comment]
gonna make user authentication soon too, i am working on a project right now, so hold tight :D

**Comment by Dev-Force** [comment]
just an annotation i just saw, TodoDao is a Model not a Document.

**Comment by Dev-Force** [comment]
i couldnt make it work nor with casting

**Comment by ericmdantas** [comment]
Alright, no worries.

About the authentication, @georgeedwards has started some changes to get that working, if you need anything, you can check it out here: https://github.com/georgeedwards/Gen-App.

**Comment by Dev-Force** [comment]
i ve already implemented it from a previous commit to an application. so i will just pass it. It will only have google+ login with oauth2 from passportjs. We can implement the rest later

**Comment by ericmdantas** [comment]
Sounds good!

**Pull request merged**
